[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.2",
    "openai>=1.107.0",
    "pinecone>=7.3.0",
    "pinecone-client>=6.0.0",
]
